workflows:
  ios-release:
    name: iOS Release Build

    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_connect

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cybrains.scamkavatchpro

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Fetch signing files
        script: xcode-project use-profiles

      - name: Build IPA
        script: flutter build ipa --release --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive